In [21]:
import pandas as pd
df = pd.read_csv("IRIS.csv")
df.head()

   sepal_length  sepal_width  petal_length  petal_width      species
0           5.1          3.5           1.4          0.2  Iris-setosa
1           4.9          3.0           1.4          0.2  Iris-setosa
2           4.7          3.2           1.3          0.2  Iris-setosa
3           4.6          3.1           1.5          0.2  Iris-setosa
4           5.0          3.6           1.4          0.2  Iris-setosa

In [22]:
# convert 3 species into 0 , 1 , 2
from sklearn.preprocessing import LabelEncoder
le  = LabelEncoder()
df["species"] = le.fit_transform(df["species"])

df.sample(10)

     sepal_length  sepal_width  petal_length  petal_width  species
134           6.1          2.6           5.6          1.4        2
80            5.5          2.4           3.8          1.1        1
90            5.5          2.6           4.4          1.2        1
127           6.1          3.0           4.9          1.8        2
70            5.9          3.2           4.8          1.8        1
109           7.2          3.6           6.1          2.5        2
14            5.8          4.0           1.2          0.2        0
87            6.3          2.3           4.4          1.3        1
61            5.9          3.0           4.2          1.5        1
131           7.9          3.8           6.4          2.0        2

In [33]:
from sklearn.model_selection import train_test_split
x = df.drop("species" , axis=1)
y = df["species"]


x_train , x_test , y_train , y_test = train_test_split(x, y, test_size=0.2, random_state=42)

In [34]:
# Logistic Regression
from sklearn.linear_model import LogisticRegression
lr = LogisticRegression(max_iter=1000)
lr.fit(x_train, y_train)

LogisticRegression(max_iter=1000)

In [35]:
# KNN
from sklearn.neighbors import KNeighborsClassifier
knn = KNeighborsClassifier(n_neighbors=5)
knn.fit(x_train, y_train)

KNeighborsClassifier()

In [36]:
# Naive Bayes
from sklearn.naive_bayes import GaussianNB
nb = GaussianNB()
nb.fit(x_train, y_train)

GaussianNB()

In [37]:
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix
models = {'Logistic Regression': lr, 'KNN': knn, 'Naive Bayes': nb}

for name, model in models.items():
    y_pred = model.predict(x)
    print(f"\n{name}")

    print("Accuracy:", accuracy_score(y, y_pred))
    
    print("cm:", confusion_matrix(y, y_pred))

    print("classification report:", classification_report(y, y_pred))

Logistic Regression
Accuracy: 0.98
cm: [[50  0  0]
 [ 0 47  3]
 [ 0  0 50]]
classification report:               precision    recall  f1-score   support

           0       1.00      1.00      1.00        50
           1       1.00      0.94      0.97        50
           2       0.94      1.00      0.97        50

    accuracy                           0.98       150
   macro avg       0.98      0.98      0.98       150
weighted avg       0.98      0.98      0.98       150


KNN
Accuracy: 0.9733333333333334
cm: [[50  0  0]
 [ 0 47  3]
 [ 0  1 49]]
classification report:               precision    recall  f1-score   support

           0       1.00      1.00      1.00        50
           1       0.98      0.94      0.96        50
           2       0.94      0.98      0.96        50

    accuracy                           0.97       150
   macro avg       0.97      0.97      0.97       150
weighted avg       0.97      0.97      0.97       150


Naive Bayes
Accuracy: 0.96
cm: [[50  0  0]
 [ 0 47  3]
 [ 0  3 47]]
classification report:               precision    recall  f1-score   support

           0       1.00      1.00      1.00        50
           1       0.94      0.94      0.94        50
           2       0.94      0.94      0.94        50

    accuracy                           0.96       150
   macro avg       0.96      0.96      0.96       150
weighted avg       0.96      0.96      0.96       150